EDA Project 2 -- Air Pollution Dataset Workbook
===============================================

Data Loading
------------

```{r pollutant data loading, cache = TRUE}
setwd('~/airpol')
download.file('https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2FNEI_data.zip',method='curl',destfile='NEI_data.zip')
unzip('NEI_data.zip')
NEI <- readRDS("summarySCC_PM25.rds")
NEI <- transform(NEI,fips=factor(fips),SCC=factor(SCC),Pollutant=as.factor(Pollutant),type=as.factor(type),year=as.factor(year))
SCC <- readRDS("Source_Classification_Code.rds")
```
Data Checking
-------------

Make sure I've got what I want ...

```{r Pollutant types check, cache = TRUE}
foo <- as.factor(NEI$Pollutant)
levels(foo)
rm(foo)
```

Question 1
----------

__Question:__ Have total emissions from PM2.5 decreased in the United States from 1999 to 2008?
Using the base plotting system, make a plot showing the total PM2.5 emission from all sources for each of the
years 1999, 2002, 2005, and 2008.

I'm gonna do this in __Plot1.R__

```{r Get year totals, cache = TRUE}
yearTotals <- as.data.frame(rowsum (NEI$Emissions, NEI$year, reorder = TRUE))
```

```{r Year total barplot, fig.width=5, fig.height=5}
barplot (yearTotals$V1, names.arg = row.names(yearTotals), main = "Nationwide Annual PM25 Pollution Totals" )
```

Question 2
----------

__Question:__ Have total emissions from PM2.5 decreased in the Baltimore City, Maryland
(fips == "24510") from 1999 to 2008? Use the base plotting system to make a plot
answering this question.

Done in __Plot2.R__

```{r Filter down to Baltimore, cache = TRUE}
baltiNEI <- NEI[NEI$fips=='24510']
baltiYearTotals <- as.data.frame(rowsum (baltiNEI$Emissions, baltiNEI$year, reorder = TRUE))
```
```{r Plot Baltimore Year Totals, fig.width=5, fig.height=5}
barplot (baltiYearTotals$V1, names.arg = row.names(baltiYearTotals), main = "Baltimore Annual PM25 Pollution Totals" )
```